[build-system]
requires = ["scikit-build-core", "nanobind"]
build-backend = "scikit_build_core.build"

[project]
name = "estimation"
version = "0.0.1"

[tool.scikit-build]
wheel.install-dir = "estimation"
